# https://docs.gitlab.com/ee/ci/yaml/

image: docker:stable

stages:
  - build
  # TODO: - tests
  - cleanup
  - deploy

variables:
  image_tag: latest

build_chat:
  stage: build
  script:
    - docker build -t interface/main:$image_tag ./chat-service

# clean up large dangling images from VM
cleanup_build:
  stage: cleanup
  script:
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
  when: on_failure
