# https://docs.gitlab.com/ee/ci/yaml/

image: docker:stable

stages:
  - build
  - tests
  - cleanup

variables:
  image_tag: latest

# check components build correctly
build_chat:
  stage: build
  script:
    - docker build -t interface/main:$image_tag ./chat-service

build_actions:
  stage: build
  script:
    - docker build -t action/server:$image_tag .

# check for the responsive deployed prototype
test_prototype:
  stage: tests
  script:
    - python tests/test_prototype.py
  tags:
    - shell

# clean up successfully built images
cleanup_successful_build:
  stage: cleanup
  script:
    - docker image rm interface/main:$image_tag
    - docker image rm action/server:$image_tag
  when: on_success
  tags:
    - shell
# clean up large dangling images from VM after failure
cleanup_failed_build:
  stage: cleanup
  script:
    - docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
    - docker system prune --force
  when: on_failure
  tags:
    - shell