version: '3.0'

services:
  database:
    image: elasticsearch:6.5.4
    ports:
      - 9200 # hide database to exterior
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - deploy
    container_name: elastic

  action_server:
    build: .
    volumes:
      - ./chat-service/model:/app/actions
    ports:
      - 5055:5055
    depends_on:
      - database
    networks:
      - deploy
    container_name: action_server

  interface:
    build: ./chat-service
    depends_on:
      - database
      - action_server
    ports:
      - 5000:5000
    networks:
      - deploy
    container_name: interface

volumes:
  esdata:

networks:
  deploy:
