version: '3'

services:
  database:
    image: elasticsearch:6.5.4
    ports:
      - "9200:9200"
  action_server:
    image: rasa/rasa_core_sdk:latest
    volumes:
      - ./chat-interface:/app/actions
    ports:
      - "5055:5055"
    command:
      - start
      - --actions
      - actions
  interface:
    build: .
    depends_on:
      - database
      - action_server
    ports:
      - "5000:5000"
