version: '3.0'

services:
  database:
    image: elasticsearch:6.5.4
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - deploy
    container_name: database

  action_server:
    build: .
    volumes:
      - ./chat-service/model:/app/actions
    ports:
      - 5055:5055
    depends_on:
      - database
    networks:
      - deploy

  interface:
    build: ./chat-service
    depends_on:
      - database
      - action_server
#      - rasa_core
#      - rasa_nlu
    ports:
      - 5000:5000
    networks:
      - deploy

volumes:
  esdata:

networks:
  deploy:

  # rasa_core:
  #   image: rasa/rasa_core:0.12.4
  #   ports:
  #     - "5005:5005"
  #   volumes:
  #     - ./chat-service/models/agent-data/models/dialogue:/app/models
  #   command:
  #     - start
  #     - --core
  #     - models
  #     - -c
  #     - rest
  #   depends_on:
  #     - rasa_nlu
  #
  # rasa_nlu:
  #   image: rasa/rasa_nlu:latest-spacy
  #   volumes:
  #     - ./chat-service/models/agent-data/models/nlu:/app/models
  #     - ./chat-service/model/nlu-config.yml:/app/config/nlu-config.yml
  #   command:
  #     - start
  #     - --path
  #     - models
  #     - -c
  #     - config/nlu-config.yml
