language: "en"

pipeline:
 - name: "nlp_spacy"
   model: "en"
 - name: "tokenizer_spacy"
 - name: "ner_crf"
# - name: "intent_featurizer_spacy"
# - name: "intent_classifier_sklearn"
# pipeline for multi intent
 - name: "intent_featurizer_count_vectors"
 - name: "intent_classifier_tensorflow_embedding"
#   intent_tokenization_flag: true
#   intent_split_symbol: "+"
